### ISSUE TITLE
Unavailable https://pkpassvalidator.azurewebsites.net :(

### ISSUE THREAD

**Issue by xavierlaffargue** [tomasmcguinness/pkpassvalidator#11]
Website https://pkpassvalidator.azurewebsites.net  is unavailable (Error 500)

**Comment by advatar** [comment]
Still not available. Can I find any documentation to run it myself?

**Comment by dmquilez** [comment]
Until @tomasmcguinness restore the service, you can run his tool on localhost through Visual Studio Code (VSC). If you aren't familiar with .NET language, VSC will guide you until you can run it. Just download or clone this project and open the folder with VSC. Then click on `Run > Start Debugging`. Consider donating a coffee to @tomasmcguinness because he has done an amazing work.

**Comment by tomasmcguinness** [comment]
Apologies for this - it all works locally. I'll take a look today if I can.

**Comment by tomasmcguinness** [comment]
I think we're back in business. I've updated the application to .Net 5 and republished as a self contained app.
